site_name: 'Moving Rainbow'
nav:
  - CoderDojo Mentor Resources: https://coderdojotc.github.io/CoderDojoTC/
  - Moving Rainbow Home: index.md
  - Getting Started:
    - Standard Kits: getting-started/kits.md
    - Purchasing Your Own Parts: getting-started/parts.md
    - Desktop Setup: getting-started/desktop-setup.md
  - Lessons:
    - Blink: lessons/blink.md
    - Fade In and Out: lessons/fade-in-and-out.md
  # - Arduino:
  #   - Getting Started: guide/getting-started.md
  #   - Hardware: guide/hardware.md
  #   - Programming Guide: guide/programming.md
  #   - List of Sample Programs: guide/list-of-sample-programs.md
  #   - Blink: guide/blink.md
  #   - Instructors Guide: guide/instructors.md
  #   - Bill of Materials: guide/bill-of-materials.md
  #   - Glossary: guide/glossary.md

site_description: 'Resources for teaching computational thinking to CoderDojo Twin Cities students using LED strips.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/dmccreary/moving-rainbow'

# CoderDojo Standards from here down
edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
plugins:
  - search
  # - mermaid2 - takes too long to build - use a screen image for now
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences
