site_name: 'Moving Rainbow'
repo_url: https://github.com/dmccreary/moving-rainbow
site_description: 'Resources for teaching computational thinking to CoderDojo Twin Cities students using LED strips.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
# repo_name: 'GitHub Repo'
edit_uri: edit/master/docs/

nav:
  - CoderDojo Mentor Resources: https://coderdojotc.github.io/CoderDojoTC/
  - Moving Rainbow Home: index.md
  - Getting Started:
    - About: getting-started/about.md
    - Standard Kits: getting-started/kits.md
    - Purchasing Your Own Parts: getting-started/parts.md
    - Desktop Setup: getting-started/desktop-setup.md
    - Updating Firmware: getting-started/updating-firmware.md
    - GitHub Summary: getting-started/github-summary.md
    - Electrical Connections: getting-started/connections.md
  - Lessons:
    - List of Lessons: lessons/index.md
    - Blink: lessons/01-blink.md
    - Fade In and Out: lessons/02-fade-in-and-out.md
    - Heartbeat: lessons/03-heartbeat.md
    - Red, Green and Blue: lessons/04-red-green-blue.md
    - Color Wheel: lessons/05-color-wheel.md
    - A Better Dimmer: lessons/06-linear-dimmer.md
    - Moving Pixel: lessons/07-motion.md
    - Rainbow: lessons/08-rainbow.md
    - Color Wipe: lessons/08-color-wipe.md
    - Random Numbers: lessons/07-random.md
    - Moving Bands: lessons/08-moving-bands.md
    - Comet Tail: lessons/09-comet-tail.md
    - Moving Rainbow: lessons/10-moving-rainbow.md
    - Larson Scanner: lessons/19-larson-scanner.md
    - Rainbow Cycle: lessons/11-rainbow-cycle.md 
    - Random: lessons/15-random.md
    - Candle Flicker: lessons/16-candle.md
    - Twinkle: lessons/18-twinkle.md
    - Ripple: lessons/18-ripple.md
    - Theater Chase: lessons/17-theater-chase.md
    - Clock: lessons/20-clock.md
    - How NeoPixels Work: lessons/40-how-neopixels-work.md
  - LED Noodles:
    - led-noodles/index.md
  - Challenges: challenges.md
  - Challenges v2: challenges-v2.md
  - Resources: resources.md
  - How we built this site: how-we-built-this-site.md
theme:
  # should be name: material
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  # - mermaid2 - takes too long to build - use a screen image for now
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences
