site_name: 'Moving Rainbow'
site_url: https://dmccreary.github.io/moving-rainbow/
repo_url: https://github.com/dmccreary/moving-rainbow
site_description: 'Resources for teaching computational thinking to CoderDojo Twin Cities students using LED strips.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
# repo_name: 'GitHub Repo'
edit_uri: edit/master/docs/

nav:
  - Course Description: course-description.md
  - Concept Sequence: concept-sequence.md  
  - Getting Started:
    - Overview: getting-started/index.md
    - About: getting-started/about.md
    - Standard Kits: getting-started/kits.md
    - Purchasing Your Own Parts: getting-started/parts.md
    - Development Boards: getting-started/dev-boards.md
    - Batteries: getting-started/batteries.md
    - Desktop Setup: getting-started/desktop-setup.md
    - Updating Firmware: getting-started/updating-firmware.md
    - GitHub Summary: getting-started/github-summary.md
    - Electrical Connections: getting-started/connections.md
    - Troubleshooting Resets: getting-started/troubleshooting-resets.md
  
  - NeoPixel Lessons:
    - List of Lessons: lessons/index.md
    - Blink: lessons/01-blink.md
    - Fade In and Out: lessons/02-fade-in-and-out.md
    - Heartbeat: lessons/03-heartbeat.md
    - Red, Green and Blue: lessons/04-red-green-blue.md
    - Color Wheel: lessons/05-color-wheel.md
    - A Better Dimmer: lessons/06-linear-dimmer.md
    - Moving Pixel: lessons/07-motion.md
    - Rainbow: lessons/08-rainbow.md
    - Color Wipe: lessons/08-color-wipe.md
    - Random Numbers: lessons/07-random.md
    - Moving Bands: lessons/08-moving-bands.md
    - Comet Tail: lessons/09-comet-tail.md
    - Moving Rainbow: lessons/10-moving-rainbow.md
    - Larson Scanner: lessons/19-larson-scanner.md
    - Rainbow Cycle: lessons/11-rainbow-cycle.md 
    - Random: lessons/15-random.md
    - Candle Flicker: lessons/16-candle.md
    - Twinkle: lessons/18-twinkle.md
    - Ripple: lessons/18-ripple.md
    - Theater Chase: lessons/17-theater-chase.md
    - Clock: lessons/20-clock.md
    - How NeoPixels Work: lessons/40-how-neopixels-work.md
    - Photo Resistor: lessons/21-photo-resistor.md
  
  - LED Noodles:
    - Introduction: led-noodles/index.md
    - Static Circuits: led-noodles/static-circuits.md
    - Calculating Battery Life: led-noodles/calculating-battery-life.md
    - LED Noodle Dimmer: led-noodles/led-noodle-dimmer.md
    - LED Noodle Nightlight: led-noodles/led-noodle-nightlight.md
    - Voltage Current Curve: led-noodles/voltage-current-curve.md
    - Project Ideas: led-noodles/project-ideas.md
    - Gamma Correction: led-noodles/gamma-correction.md
    - Dynamic Projects: led-noodles/dynamic-projects.md
  
  - MicroSims:
    - Introduction: sims/index.md
    - Battery Life Calculator: sims/battery-life-calculator/index.md
    - Solar Powered LED Nightlight: sims/solar-powered-nightlight/index.md
    - Color Wheel: sims/color-wheel/index.md
    - Learning Graph: sims/learning-graph/index.md
    - LED Current Predictor: sims/current-predictor/index.md
  
  - Kits:
    - Intro: kits/index.md
    - Base Moving Rainbow Kit: kits/moving-rainbow-base/index.md
    - 8x8 NeoPixel: kits/8x8-neopixel-matrix/index.md
    - Solar Powered Nightlight:
      - Intro: kits/solar-powered-led-nightlight/index.md
      - kits/solar-powered-led-nightlight/how-it-works.md
      - kits/solar-powered-led-nightlight/microsim.md
      - kits/solar-powered-led-nightlight/prompt.md
    
    - Holiday Hats:
      - Intro: kits/holiday-hats/index.md
      - Valentine's Day: kits/holiday-hats/valentines-day.md
      - 4th of July: kits/holiday-hats/4th-of-july.md
      - St. Patrick's Day: kits/holiday-hats/st-patricks-day.md
      - Halloween: kits/holiday-hats/halloween.md
      - Christmas: kits/holiday-hats/christmas.md
      - Valentine's Day: kits/holiday-hats/valentines-day.md
    
    - Halloween Patterns:
      - Intro: kits/halloween/index.md
    - Jake's Fire:
      - Intro: kits/jakes-fire/index.md
      - Advanced Version: kits/jakes-fire/advanced-version.md
    
    - kits/analog-nightlight/index.md
    - kits/digital-nightlight/index.md
    
    - kits/led-fire/index.md
    - kits/led-nightlight/index.md
    - kits/led-noodle-nightlight/index.md
  
  - Teachers Guide:
    - Introduction: teachers-guide/index.md
    - Computational Thinking: teachers-guide/computational-thinking.md
    - Concept Cards: teachers-guide/concept-cards.md
    - teachers-guide/code-group-status.md
    - teachers-guide/code-of-conduct.md
    - teachers-guide/content-authoring-guide.md
    - teachers-guide/designing-concept-cards.md
    - teachers-guide/journey-maps.md
    - teachers-guide/mentoring-best-practices.md
    - teachers-guide/rhizomatous-learning-theory.md
  
<<<<<<< HEAD
  - Kits:
    - Introduction: kits/index.md
    - Base Moving Rainbow Kit: kits/base-moving-rainbow-kit/index.md
    - NeoPixel Matrix: kits/8x8-neopixel-matrix/index.md
    - Solar Powered Nightlight:
      - Intro: kits/solar-powered-led-nightlight/index.md
      - How it works: kits/solar-powered-led-nightlight/how-it-works.md
      - MicroSim: kits/solar-powered-led-nightlight/microsim.md
      - Prompt: kits/solar-powered-led-nightlight/prompt.md
    - LED Noodle Nightlight:
      - Intro: kits/analog-nightlight/index.md
      - Digital Nightlight: kits/digital-nightlight/index.md
      - kits/led-noodle-nightlight/index.md
    - LED Fire: kits/led-fire/index.md
    - kits/led-nightlight/index.md
  
=======
>>>>>>> c815edeceb2f503eaa77d95393b3af2a3f49f96e
  - GenAI Prompts:
    - Introduction: prompts/index.md
    - Moving Rainbow: prompts/moving-rainbow.md
    - Course Description: prompts/course-description.md
    - Concept Dependency: prompts/concept-dependency-graph.md
    - Concept Taxonomy: prompts/concept-taxonomy.md
    - Generate Claude Skill: prompts/generate-skill.md
    - Generating a Glossary: prompts/glossary.md
<<<<<<< HEAD

=======
    - Learning Graph:
      - Intro: prompts/learning-graph-intro.md
      - Course Description: prompts/course-description.md
      - Concept Dependency: prompts/concept-dependency-graph.md
      - Concept Taxonomy: prompts/concept-taxonomy.md
    - Cover: prompts/cover-image.md
>>>>>>> c815edeceb2f503eaa77d95393b3af2a3f49f96e
  - Challenges: challenges.md
  - Challenges v2: challenges-v2.md
  - License: license.md
  - Glossary: glossary.md
  - Resources: resources.md
  - How we built this site: how-we-built-this-site.md

# Dan's Intelligent books standards from here down
theme:
  # should be name: material
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
  - social_override
  # - mermaid2 - takes too long to build - use a screen image for now
markdown_extensions:
  - meta
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.tabbed
# enable LaTeX equation rendering
  - pymdownx.arithmatex:
      generic: true
extra_css:
   - css/extra.css
extra_javascript:
    - js/extra.js
    # needed for mathjax to work
    # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
